# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0003_auto_20180426_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
